# Site settings
title: Myrkviðr
email: hayden.elza@gmail.com
description: >
  Hey there reader! My name is Hayden Elza and this is my blog spanning
  a wide range of interests from programming and linux to sailing and
  backpacking. This media serves sort of as a constant stream of consciousness,
  as such content is likely as erratic as my mind.
baseurl: "/blog" 
url: "localhost:4000" 
twitter_username: haydenelza
github_username:  haydenelza

# Build settings
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: /:year/:month/:title
