# Site settings
title: Hayden Elza
email: hayden.elza@gmail.com
description: >
  Hayden Elza's Blog
baseurl: "/blog" 
url: "elza.me" 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
permalink: /:year/:month/:title/
